#!/usr/bin/env python
# -*- coding: utf-8 -*-

# SPDX-License-Identifier: BSD-3-Clause
# Copyright Contributors to the SMTPE RIS OSVP Metadata Project

'''Mo-Sys CLI tool'''

import json
import argparse
import camdkit.framework
import camdkit.mosys.reader

def main():
  parser = argparse.ArgumentParser(description="Convert Mo-Sys F4 tracking metadata to JSON according to the OSVP Camera Metadata Model.")
  parser.add_argument(
    'frame_f4_path',
    type=str,
    help="Path to F4 file containing Mo-Sys camera tracking data"
    )

  args = parser.parse_args()

  # First 10 frames
  frames = camdkit.mosys.reader.to_frames(args.frame_f4_path, 10)
  print("Simple packet example generated by CamDKit's Mo-Sys F4 reader")
  print("RAW")
  print(json.dumps(frames[0], indent=2))
  print()

  # First frame prettified
  frame = camdkit.mosys.reader.to_clip(args.frame_f4_path, 1)
  print("PRETTY")
  print(json.dumps(frame.prettify(), indent=2))
  
if __name__ == "__main__":
  main()
